name: Publish iOS
on:
  release:
    types: [ created ]
jobs:
  upload-xcframework:
    runs-on: [ "macos-14" ]
    env:
      TERM: xterm
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Build and Test Framework
        run: |
          brew install protobuf
          cargo clean
          make clean-mobile-build
          make test-ios
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.git_pass }}
        with:
          name: ${{ github.event.release.name }}
          files: ./packages/kos-mobile/ios/XCFrameworks/KOSMobile.xcframework.zip