name: Publish iOS
on:
  release:
    types: [ created ]
jobs:
  upload-xcframework:
    runs-on: [ "macos-14" ]
    env:
      TERM: xterm
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Build and Test Framework
        run: |
          brew install protobuf
          cargo clean
          make clean-mobile-build
          make test-ios
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./packages/kos-mobile/ios/XCFrameworks/
          asset_name: KOSMobile.xcframework.zip
          asset_content_type: application/zip