name: Bump version && Release KOS-RS

on:
  workflow_dispatch:
    inputs:
        versionType:
          description: 'Version Type'
          required: true
          default: 'patch'
          type: choice
          options:
          - major
          - minor
          - patch
permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      USER: ${{ secrets.GIT_USER }}
      TOKEN: ${{ secrets.GIT_PASS }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
        
      - name: Bump version
        run: bash .github/actions/bump-version.sh ${{ inputs.versionType }}
  
      - name: RustUp
        uses: klever-io/kos-rs/.github/actions/rustup@develop
        with:
          with_cache: true

      - name: Build
        run: make webpack-npm

      - name: Setup npm module
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@klever'
          always-auth: true

      - name: Publish npm module
        run: npm publish ./demo/kos --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
